export interface FileAttachment {
  id: string;
  name: string;
  size: number;
  type: string;
  content: string; // base64 encoded
}

export interface Message {
  id?: string; // Optional: Generated by DB on insert
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
  attachments?: FileAttachment[];
}

export interface Settings {
  apiKey: string;
  baseUrl: string;
  model: string;
}